spring.application.name=core-service
server.port=8080

# Generic JPA / Hibernate Properties (Applies to all databases)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

gateway.services.common=http://localhost:8081
gateway.services.authentication=http://localhost:8082
gateway.services.file=http://localhost:8083
gateway.services.processing=http://localhost:8084