spring.application.name=core-service
server.port=8080

# Generic JPA / Hibernate Properties (Applies to all databases)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.tomcat.connection-timeout=60000
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB